# .streamlit/config.toml

# Define a configuração do tema da aplicação
[theme]

# Cor primária para os elementos interativos (botões, sliders, etc.)
# Exemplo: um tom de azul vibrante
primaryColor = "#7792E3"

# Cor de fundo principal da aplicação
# Forçando um tom escuro
backgroundColor = "#0E1117"

# Cor de fundo para elementos secundários (como a sidebar)
secondaryBackgroundColor = "#262730"

# Cor do texto principal
textColor = "#FAFAFA"

# Fonte a ser usada (sans serif, serif, or monospace)
font = "sans serif"

# Define o tema base como "dark" (escuro).
# Esta é a linha mais importante para o seu pedido.
base = "dark"
