[theme]
# Cor principal, usada em botões e elementos interativos
primaryColor="#FFA500"  # Um laranja, por exemplo

# Cor de fundo principal da aplicação
backgroundColor="#F0F2F6" # Um cinza bem claro

# Cor de fundo de elementos como a barra lateral e caixas de código
secondaryBackgroundColor="#FFFFFF" # Branco

# Cor do texto principal
textColor="#262730" # Um cinza escuro

# Cor da fonte
font="sans serif"