SHEET_URL = "https://docs.google.com/spreadsheets/d/1d6awYGDkfQwuFyolzWod4Y2phJlWDLr0FhRjEP2W0E8/edit?usp=sharing"
FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLSe01y50r_ludi77tqoORt1pTrFSAycW37cGoYZgbRApLMDFPA/viewform"
MANUTENCAO_FORM_URL = "https://docs.google.com/forms/d/e/1FAIpQLSdtVpHGzXrBTRzx5-XYCmvtp9mVYB6Z1XA0q_lbwCKZJ55xpw/viewform"
